site_name: Book of Azure
site_url: https://bookofazure.com/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  logo: assets/logo/logo.png
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: lime

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lukemurraynz/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lukemurraynz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ljmurray/

  analytics:
    provider: google
    property: G-7Y196JE6RW

  nav:
    - 'index.md'
    - 'GettingStarted.md'
    - 'DeployingIaaSPaaS.md'
    - 'ArchitectHA.md'
    - 'AdvAzure.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

site_author: Luke Murray
copyright: |
  &copy; 2023 <a href="https://github.com/lukemurraynz/"  target="_blank" rel="noopener">Luke Murray</a>

plugins:
    - with-pdf:
        author: Luke Murray
        copyright: '@2023'
        #
        #cover: false
        cover_title: Book of Azure
        cover_subtitle: Whosoever holds this book, if they be worthy, shall possess the power of Azure.
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        output_path: pdf/bookofazure.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #verbose: true