site_name: Book of Azure
site_url: https://bookofazure.com/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lukemurraynz/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lukemurraynz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ljmurray/

  nav:
    - Title: 'index.md'
    - Chapter 1: 'GettingStarted.md'
    - Chapter 2: 'DeployingIaaSPaaS.md'
    - Chapter 3: ArchitectHA.md'
    - Chapter 4: 'AdvAzure.md'
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

site_author: Luke Murray
copyright: |
  &copy; 2023 <a href="https://github.com/lukemurraynz/"  target="_blank" rel="noopener">Luke Murray</a>

